### ISSUE TITLE
Component libraries

### ISSUE THREAD

**Issue by cores-system** [aspnet/Blazor#1188]
Hello, is there an example of this https://github.com/aspnet/Blazor/issues/340 solution at Blazor 0.4.0?

**Comment by lohithgn** [comment]
Hi. What are you looking for? The structure will work in  0.4.0. Can you elaborate your question?

**Comment by cores-system** [comment]
Complains of an error

```
Severity Code Description Project File String Suppression State
Error CS0246 The type or name of the "MyLibrary" namespace could not be found (maybe there is no using directive or link to the assembly). WebApplication7 C: \ Users \ htc \ Desktop \ ModularBlazorWebApp-master \ WebApplication7 \ obj \ Debug \ netstandard2.0 \ App.g.i.cs 22 Active
```

example
https://github.com/cores-system/ModularBlazorWebApp

**Comment by cores-system** [comment]
Тему можно закрывать, неправильно указал настройки .csproj для librarie.

Working example
https://github.com/cores-system/BlazorSPA
